version: '2'
services:
    db:
        image: mysql
        volumes:
            - .sql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mes
        ports:
            - '3306:3306'

    app:
        depends_on:
            - db
        ports:
            - "3000:3000"
        build: .
        volumes:
            - .:/app

    sqladmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        links:
            - db
